kfghslnvhfgnnhgjhnddghnvgnbnhgfgjdjhgddfjdkdkgvghfkjgvvndfjvnhnhjnjdfjvhjvnhndvbgfvvvdfjvjhjgfhhvfvfvgfvgfvgfnjgfhjffvgfvnjgfvnhjf=input
gtthjgnjdfkjidikikdikkdijdkifh=range
joinvaaniyousobs=ord
macinshit=2
fhyfjigfhyjhbyfgkdjdgfkldfhghbrj = kfghslnvhfgnnhgjhnddghnvgnbnhgfgjdjhgddfjdkdkgvghfkjvvndfjvnhnhjnjdfjvhjvnhndvbgfvvvdfjvjhjgfhhvfvfvgfvgfvgfnjgfhjffvgfvnjgfvnhjf()
cometocluborientatioonoruisgay = ''
for singyoufools in gtthjgnjdfkjidikikdikkdijdkifh(0,len(fhyfjigfhyjhbyfgkdjdgfkldfhghbrj),macinshit):
    cometocluborientatioonoruisgay+=chr(int((joinvaaniyousobs(fhyfjigfhyjhbyfgkdjdgfkldfhghbrj[singyoufools])*joinvaaniyousobs(fhyfjigfhyjhbyfgkdjdgfkldfhghbrj[singyoufools+macinshit//2]))**(macinshit/4)))
print(cometocluborientatioonoruisgay)